name: IMPLEMENTACION DE CI/CD CON GITHUB ACTIONS – DOCKER

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies node
        run: npm install

      - name: Check code with ruff
        run: echo "skip ruff"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/edwingaa/devops-barberia:latest